services:
  web:
    build: https://github.com/Klingdom/applied-compassion-benchmark.git
    container_name: compassion-benchmark
    ports:
      - "8080:80"
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true
